create table if not     exists bank_details (
age int ,
job varchar(30) ,
marital varchar(30) ,
education varchar(30),
`default` varchar(30),
balance int,
housing varchar(30) ,
loan varchar(30) ,
contact varchar(30) ,
`day` int ,
`month` varchar(30) ,
duration int ,
campaign int ,
pdays int ,
previous int ,
poutcome varchar(30),
y varchar(30))
